// flow-typed signature: 65eb1ffafb88823edd7d41f1109b9c83
// flow-typed version: <<STUB>>/jest-expo_v~0.4.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-expo/src/bridgeMock' {
  declare module.exports: any;
}

declare module 'jest-expo/src/exponentModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/index' {
  declare module.exports: any;
}

declare module 'jest-expo/src/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-expo/src/bridgeMock.js' {
  declare module.exports: $Exports<'jest-expo/src/bridgeMock'>;
}
declare module 'jest-expo/src/exponentModules.js' {
  declare module.exports: $Exports<'jest-expo/src/exponentModules'>;
}
declare module 'jest-expo/src/index.js' {
  declare module.exports: $Exports<'jest-expo/src/index'>;
}
declare module 'jest-expo/src/setup.js' {
  declare module.exports: $Exports<'jest-expo/src/setup'>;
}
