export const CHANGE_EXERCISE = 'CHANGE_EXERCISE';
export const NEXT_EXERCISE = 'NEXT_EXERCISE';
export const SUBMIT_EXERCISE = 'SUBMIT_EXERCISE';
export const CHANGE_EXERCISE_ANSWER = 'CHANGE_EXERCISE_ANSWER';
