// flow-typed signature: 7e8e320c150e95236f7d7787e76ae368
// flow-typed version: <<STUB>>/@kadira/react-native-storybook_v^2.2.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/react-native-storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/react-native-storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/react-native-storybook/addons' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/bin/storybook-build' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/bin/storybook-start' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/bin/storybook' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/index' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/manager/index' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/manager/provider' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/preview/components/StoryView/index' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/preview/components/StoryView/style' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/preview/index' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/preview/story_kind' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/preview/story_store' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/addons' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config/babel' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config/babel.prod' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config/defaults/webpack.config' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config/utils' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config/webpack.config' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/index.html' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/index' {
  declare module.exports: any;
}

declare module '@kadira/react-native-storybook/dist/server/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/react-native-storybook/addons.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/addons'>;
}
declare module '@kadira/react-native-storybook/dist/bin/storybook-build.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/bin/storybook-build'>;
}
declare module '@kadira/react-native-storybook/dist/bin/storybook-start.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/bin/storybook-start'>;
}
declare module '@kadira/react-native-storybook/dist/bin/storybook.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/bin/storybook'>;
}
declare module '@kadira/react-native-storybook/dist/index.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/index'>;
}
declare module '@kadira/react-native-storybook/dist/manager/index.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/manager/index'>;
}
declare module '@kadira/react-native-storybook/dist/manager/provider.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/manager/provider'>;
}
declare module '@kadira/react-native-storybook/dist/preview/components/StoryView/index.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/preview/components/StoryView/index'>;
}
declare module '@kadira/react-native-storybook/dist/preview/components/StoryView/style.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/preview/components/StoryView/style'>;
}
declare module '@kadira/react-native-storybook/dist/preview/index.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/preview/index'>;
}
declare module '@kadira/react-native-storybook/dist/preview/story_kind.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/preview/story_kind'>;
}
declare module '@kadira/react-native-storybook/dist/preview/story_store.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/preview/story_store'>;
}
declare module '@kadira/react-native-storybook/dist/server/addons.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/addons'>;
}
declare module '@kadira/react-native-storybook/dist/server/config.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config'>;
}
declare module '@kadira/react-native-storybook/dist/server/config/babel.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config/babel'>;
}
declare module '@kadira/react-native-storybook/dist/server/config/babel.prod.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config/babel.prod'>;
}
declare module '@kadira/react-native-storybook/dist/server/config/defaults/webpack.config.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config/defaults/webpack.config'>;
}
declare module '@kadira/react-native-storybook/dist/server/config/utils.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config/utils'>;
}
declare module '@kadira/react-native-storybook/dist/server/config/webpack.config.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config/webpack.config'>;
}
declare module '@kadira/react-native-storybook/dist/server/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/config/webpack.config.prod'>;
}
declare module '@kadira/react-native-storybook/dist/server/index.html.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/index.html'>;
}
declare module '@kadira/react-native-storybook/dist/server/index.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/index'>;
}
declare module '@kadira/react-native-storybook/dist/server/middleware.js' {
  declare module.exports: $Exports<'@kadira/react-native-storybook/dist/server/middleware'>;
}
